### ISSUE TITLE
Unable to clone swd_recorder project

### ISSUE THREAD

**Issue by gregma** [sergueik/selenium_java#2]
It seems to be just a directory of the much larger project?  Do we need all that code just to use/work on SWET?  Can the SWET project be renamed and moved outside the selenium_java project? No other code from `selenium_java` is needed for SWET

**Comment by sergueik** [comment]
renaming tonight or tomorrow.  Please stay tuned

**Comment by sergueik** [comment]
created a separate project and copied into the project the BreadCrumb widget from  external repository which jar is  not maven-hosted. How the project can be built and run from eclipse

**Comment by gregma** [comment]
Thank you!  I'll give it a lookover this week.
